% Professional Washing Machine Fuzzy Inference System UI
% Interactive MATLAB dashboard for estimating wash time using fuzzy logic.

clc;
clear;
close all;

% Build FIS once and reuse it in callbacks.
fis = localBuildFIS();

% Create the main application window.
fig = uifigure( ...
    'Name', 'SmartWash Pro - Fuzzy Washing Machine Controller', ...
    'Position', [100 80 1280 720], ...
    'Color', [0.96 0.97 0.99]);

mainGrid = uigridlayout(fig, [3 4]);
mainGrid.RowHeight = {70, '1x', 160};
mainGrid.ColumnWidth = {300, 340, '1x', 320};
mainGrid.Padding = [18 18 18 18];
mainGrid.RowSpacing = 14;
mainGrid.ColumnSpacing = 14;

% Header section
headerPanel = uipanel(mainGrid, ...
    'BackgroundColor', [0.08 0.20 0.38], ...
    'BorderType', 'none');
headerPanel.Layout.Row = 1;
headerPanel.Layout.Column = [1 4];

uilabel(headerPanel, ...
    'Text', 'SmartWash Pro', ...
    'FontSize', 28, ...
    'FontWeight', 'bold', ...
    'FontColor', [1 1 1], ...
    'Position', [20 22 260 32]);

uilabel(headerPanel, ...
    'Text', 'Mamdani fuzzy inference dashboard for intelligent wash-cycle control', ...
    'FontSize', 13, ...
    'FontColor', [0.87 0.92 0.98], ...
    'Position', [290 28 560 22]);

% Control panel
controlPanel = uipanel(mainGrid, ...
    'Title', 'Control Inputs', ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [1 1 1]);
controlPanel.Layout.Row = 2;
controlPanel.Layout.Column = 1;

uilabel(controlPanel, ...
    'Text', 'Dirt Level (0-10)', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'Position', [20 255 180 22]);

dirtSlider = uislider(controlPanel, ...
    'Limits', [0 10], ...
    'MajorTicks', 0:2:10, ...
    'Value', 5, ...
    'Position', [25 245 240 3]);

dirtValue = uilabel(controlPanel, ...
    'Text', '5.0', ...
    'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'Position', [210 255 60 22]);

uilabel(controlPanel, ...
    'Text', 'Load Size (0-10)', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'Position', [20 170 180 22]);

loadSlider = uislider(controlPanel, ...
    'Limits', [0 10], ...
    'MajorTicks', 0:2:10, ...
    'Value', 5, ...
    'Position', [25 160 240 3]);

loadValue = uilabel(controlPanel, ...
    'Text', '5.0', ...
    'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'Position', [210 170 60 22]);

statusBox = uitextarea(controlPanel, ...
    'Value', {'System ready.'}, ...
    'Editable', 'off', ...
    'FontSize', 12, ...
    'BackgroundColor', [0.97 0.98 1.00], ...
    'Position', [20 20 250 110]);

% Result panel
resultPanel = uipanel(mainGrid, ...
    'Title', 'Decision Output', ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [1 1 1]);
resultPanel.Layout.Row = 2;
resultPanel.Layout.Column = 2;

washGauge = uigauge(resultPanel, 'semicircular');
washGauge.Position = [50 120 230 130];
washGauge.Limits = [0 60];
washGauge.MajorTicks = 0:10:60;
washGauge.Value = 30;
washGauge.ScaleColors = [ ...
    0.15 0.70 0.35
    0.95 0.72 0.18
    0.84 0.22 0.23];
washGauge.ScaleColorLimits = [0 20; 20 40; 40 60];

resultTitle = uilabel(resultPanel, ...
    'Text', 'Estimated Wash Time', ...
    'FontSize', 17, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'Position', [45 260 240 24]);

resultLabel = uilabel(resultPanel, ...
    'Text', '30.00 minutes', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'FontColor', [0.08 0.20 0.38], ...
    'Position', [40 80 250 32]);

cycleLabel = uilabel(resultPanel, ...
    'Text', 'Recommended Cycle: Normal Wash', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'center', ...
    'Position', [30 48 270 24]);

% Surface panel
surfacePanel = uipanel(mainGrid, ...
    'Title', 'Wash-Time Response Surface', ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [1 1 1]);
surfacePanel.Layout.Row = 2;
surfacePanel.Layout.Column = 3;

surfaceAxes = uiaxes(surfacePanel);
surfaceAxes.Position = [15 15 520 305];
surfaceAxes.Box = 'on';
surfaceAxes.FontSize = 11;
surfaceAxes.View = [-35 28];
surfaceAxes.XLabel.String = 'Dirt Level';
surfaceAxes.YLabel.String = 'Load Size';
surfaceAxes.ZLabel.String = 'Wash Time (min)';
title(surfaceAxes, 'Fuzzy Surface Viewer');

% Summary panel
summaryPanel = uipanel(mainGrid, ...
    'Title', 'System Insight', ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [1 1 1]);
summaryPanel.Layout.Row = 2;
summaryPanel.Layout.Column = 4;

summaryText = uitextarea(summaryPanel, ...
    'Editable', 'off', ...
    'FontSize', 13, ...
    'BackgroundColor', [1 1 1], ...
    'Position', [15 15 275 305]);

% Bottom information cards
casePanel = uipanel(mainGrid, ...
    'Title', 'Case Study', ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [1 1 1]);
casePanel.Layout.Row = 3;
casePanel.Layout.Column = [1 2];

caseText = uitextarea(casePanel, ...
    'Editable', 'off', ...
    'FontSize', 12, ...
    'BackgroundColor', [1 1 1], ...
    'Value', { ...
        'Example input:', ...
        'Dirt Level = 8', ...
        'Load Size = 9', ...
        'Expected result: approximately 55-60 minutes', ...
        '', ...
        'Interpretation:', ...
        'Heavier dirt and larger loads increase wash duration,', ...
        'which makes the controller behave realistically.'}, ...
    'Position', [15 10 590 110]);

rulePanel = uipanel(mainGrid, ...
    'Title', 'Rule Highlights', ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [1 1 1]);
rulePanel.Layout.Row = 3;
rulePanel.Layout.Column = [3 4];

ruleText = uitextarea(rulePanel, ...
    'Editable', 'off', ...
    'FontSize', 12, ...
    'BackgroundColor', [1 1 1], ...
    'Value', { ...
        '1. Low dirt + small load -> short wash', ...
        '2. Low dirt + large load -> medium wash', ...
        '3. Medium dirt + medium load -> medium wash', ...
        '4. Medium dirt + large load -> long wash', ...
        '5. High dirt with any meaningful load -> long wash'}, ...
    'Position', [15 10 600 110]);

% Precompute the surface for a cleaner, faster UI.
[dirtGrid, loadGrid] = meshgrid(0:0.25:10, 0:0.25:10);
washGrid = evalfis(fis, [dirtGrid(:) loadGrid(:)]);
washGrid = reshape(washGrid, size(dirtGrid));
surf(surfaceAxes, dirtGrid, loadGrid, washGrid, 'EdgeColor', 'none');
colormap(surfaceAxes, turbo);
colorbar(surfaceAxes);
hold(surfaceAxes, 'on');
marker3D = plot3(surfaceAxes, 5, 5, 30, 'ko', ...
    'MarkerFaceColor', [1 1 1], ...
    'MarkerSize', 8);
hold(surfaceAxes, 'off');

% Wire callbacks for live updates.
dirtSlider.ValueChangingFcn = @(src, event) updateDashboard(event.Value, loadSlider.Value);
loadSlider.ValueChangingFcn = @(src, event) updateDashboard(dirtSlider.Value, event.Value);
dirtSlider.ValueChangedFcn = @(src, event) updateDashboard(src.Value, loadSlider.Value);
loadSlider.ValueChangedFcn = @(src, event) updateDashboard(dirtSlider.Value, src.Value);

% First render.
updateDashboard(dirtSlider.Value, loadSlider.Value);

function updateDashboard(dirtLevel, loadSize)
    washTime = evalfis(fis, [dirtLevel loadSize]);

    dirtValue.Text = sprintf('%.1f', dirtLevel);
    loadValue.Text = sprintf('%.1f', loadSize);
    resultLabel.Text = sprintf('%.2f minutes', washTime);
    washGauge.Value = washTime;

    cycleName = localCycleName(washTime);
    soilLabel = localBandName(dirtLevel, {'Low', 'Medium', 'High'});
    loadLabel = localBandName(loadSize, {'Small', 'Medium', 'Large'});

    cycleLabel.Text = ['Recommended Cycle: ' cycleName];
    statusBox.Value = { ...
        'Live system status:', ...
        ['Dirt profile: ' soilLabel], ...
        ['Load profile: ' loadLabel], ...
        ['Inference result: ' sprintf('%.2f minutes', washTime)], ...
        ['Decision class: ' cycleName]};

    summaryText.Value = { ...
        'Design summary:', ...
        'The Mamdani controller blends two inputs using fuzzy rules', ...
        'so the machine responds smoothly instead of switching abruptly.', ...
        '', ...
        'Current interpretation:', ...
        [sprintf('With dirt = %.1f and load = %.1f,', dirtLevel, loadSize)], ...
        ['the system selects ' cycleName ' with an estimated duration of ' ...
         sprintf('%.2f minutes.', washTime)], ...
        '', ...
        'Why it looks intelligent:', ...
        'Wash time grows as dirt and load increase, which matches real', ...
        'washing-machine behavior and is easy to explain in a viva.'};

    marker3D.XData = dirtLevel;
    marker3D.YData = loadSize;
    marker3D.ZData = washTime;
end

function label = localCycleName(washTime)
    if washTime < 20
        label = 'Quick Wash';
    elseif washTime < 40
        label = 'Normal Wash';
    else
        label = 'Deep Wash';
    end
end

function label = localBandName(value, labels)
    if value < 3.5
        label = labels{1};
    elseif value < 6.5
        label = labels{2};
    else
        label = labels{3};
    end
end

function fis = localBuildFIS()
    fis = mamfis('Name', 'WashingMachineCycle');

    fis = addInput(fis, [0 10], 'Name', 'DirtLevel');
    fis = addMF(fis, 'DirtLevel', 'trimf', [0 0 4], 'Name', 'Low');
    fis = addMF(fis, 'DirtLevel', 'trimf', [2 5 8], 'Name', 'Medium');
    fis = addMF(fis, 'DirtLevel', 'trimf', [6 10 10], 'Name', 'High');

    fis = addInput(fis, [0 10], 'Name', 'LoadSize');
    fis = addMF(fis, 'LoadSize', 'trimf', [0 0 4], 'Name', 'Small');
    fis = addMF(fis, 'LoadSize', 'trimf', [2 5 8], 'Name', 'Medium');
    fis = addMF(fis, 'LoadSize', 'trimf', [6 10 10], 'Name', 'Large');

    fis = addOutput(fis, [0 60], 'Name', 'WashTime');
    fis = addMF(fis, 'WashTime', 'trimf', [0 0 20], 'Name', 'Short');
    fis = addMF(fis, 'WashTime', 'trimf', [15 30 45], 'Name', 'Medium');
    fis = addMF(fis, 'WashTime', 'trimf', [40 60 60], 'Name', 'Long');

    rules = [ ...
        1 1 1 1 1
        1 2 1 1 1
        1 3 2 1 1
        2 1 2 1 1
        2 2 2 1 1
        2 3 3 1 1
        3 1 3 1 1
        3 2 3 1 1
        3 3 3 1 1];

    fis = addRule(fis, rules);
end
